### ISSUE TITLE
这正是我需要的插件，请增加以下功能。

### ISSUE THREAD

**Issue by nanjingman** [astradev123/obsidian-focus-time#1]
1、可在frontmatter中自动增加对应字段如（focustime）并即时更新时间。
2、可增加时间段筛选器，筛选起始时段focustime列表（自高到低排序）。
3、可增加显示笔记数数量而不仅限于现有的10项。
4、界面也许可以参照viewcount这个插件。
![image](https://github.com/user-attachments/assets/19f53bc0-02d3-4e5d-99c0-4cc1d5b55ac2)

非常感谢！

**Comment by astradev123** [comment]
感谢你的建议！目前插件处于第一个发布版本，功能并不完善。在后续的版本中，这些功能将会逐步加入。
